import { Collection, Document, QueryParams, QueryOptions, VectorSearchOptions } from '@/types'
import { FetchDocument } from './document'
import { buildUrl, buildQueryString } from './utils'
import { logger } from '@/utils/logger'
import { DocumentNotFoundError, ValidationError } from '@/utils/errors'
import { validateDocument, validateQueryParams } from '@/utils/validation'